###
POST http://127.0.0.1:6001/v1/register/
Content-Type: application/json

{"nickname":"你好","password":"123456", "email":"stl@frytea.com"}

###
POST http://127.0.0.1:6001/v1/login
Content-Type: application/json

{"username":"stl@frytea.com","password":"123456"}

###
POST http://127.0.0.1:6001/v1/login
Content-Type: application/json

{"username":"1305647042@qq.com","password":"tianlun666"}

###
GET http://127.0.0.1:6001/v1/u/651/logout
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXNJblZwWkNJNk5qVXhMQ0oxWDI1aGJXVWlPaUp6ZEd3eElpd2lkVjloWkdSeUlqb2lNVEkzTGpBdU1DNHhJaXdpY25SZmFXUWlPamcyTENKbGVIQWlPakUyTkRjNE5ESTFNekVzSW1saGRDSTZNVFkwTnpnME1UWXpNU3dpYm1KbUlqb3hOalEzT0RReE5qTXhmUS5GRExyNWxVbVBUTG51OUZaa19OUGNqRkZJRnY0MGVBbmVJSVZFSDkyX09R

###
GET http://127.0.0.1:6001/v1/u/a/list
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXdMQ0oxYVdRaU9qSXNJblZmYm1GdFpTSTZJbUZrYldsdU1TSXNJblZmWVdSa2NpSTZJakV5Tnk0d0xqQXVNU0lzSW1WNGNDSTZNVFkwTnpNeU9EZ3hNU3dpYVdGMElqb3hOalEzTXpJM09URXhMQ0p1WW1ZaU9qRTJORGN6TWpjNU1URjkuZ041dmhmb0o2ek1nYjItbWJWSWpHVkZwWWZsbE1jWF9OQzFjS2dOc3Z6aw==
Content-Type: application/json

###
GET http://127.0.0.1:6001/v1/u/651/refresh
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXNJblZwWkNJNk5qVXhMQ0oxWDI1aGJXVWlPaUp6ZEd3eElpd2lkVjloWkdSeUlqb2lNVEkzTGpBdU1DNHhJaXdpY25SZmFXUWlPakFzSW1WNGNDSTZNVFkwT0RVek16azJNU3dpYVdGMElqb3hOalEzT1RJNU1UWXhMQ0p1WW1ZaU9qRTJORGM1TWpreE5qRjkuZFNjZVJQWFJFZFdnbUVtVHBnWHhyN3JEbnZBNWY3bTB3aG85OGVWZVMwVQ==

###
PUT http://127.0.0.1:6001/v1/u/2/pref
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXNJblZwWkNJNk1pd2lkVjl1WVcxbElqb2lZV1J0YVc0eElpd2lkVjloWkdSeUlqb2lNVEkzTGpBdU1DNHhJaXdpWlhod0lqb3hOalEzTXpFd09UUTBMQ0pwWVhRaU9qRTJORGN6TVRBd05EUXNJbTVpWmlJNk1UWTBOek14TURBME5IMC5oRTg3WDZ5akRwUDNOYV9uakNPdXNrRWxrcElVd0xmQzVCZVJraW1QemhZ
Content-Type: application/json

{
  "notion_token": "secret_7PGIsvNANvEuuFieGlPTsCqLfVISsNUFt2bhrW4OnvU",
  "notion_bills_id": "bdfd5389bc314092a7a05ead398d7bf3",
  "notion_account_id": "2ac0c304e60c454ba4997763c541d769",
  "notion_investment_id": "10f277d286f142dd9714e63a3445e542",
  "notion_investment_account_id": "7729edfb19f44742b6832734edc51393",
  "notion_budget_id": "2bfcf2e1fec845f19333c7706ee35e27"
}

###
GET http://127.0.0.1:6001/v1/u/2/pref
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXNJblZwWkNJNk1pd2lkVjl1WVcxbElqb2lZV1J0YVc0eElpd2lkVjloWkdSeUlqb2lNVEkzTGpBdU1DNHhJaXdpWlhod0lqb3hOalEzTXpJMk56UXlMQ0pwWVhRaU9qRTJORGN6TWpVNE5ESXNJbTVpWmlJNk1UWTBOek15TlRnME1uMC4xOGY3cnI4TTRHTXdJYldsVUt3YXVWaEhxck5YUTMwdGg2aFNpNktWQ2M4

###
GET http://127.0.0.1:6001/v1/u/2
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXdMQ0oxYVdRaU9qSXNJblZmYm1GdFpTSTZJbUZrYldsdU1TSXNJblZmWVdSa2NpSTZJakV5Tnk0d0xqQXVNU0lzSW1WNGNDSTZNVFkwTnpNeU9UZ3hNeXdpYVdGMElqb3hOalEzTXpJNE9URXpMQ0p1WW1ZaU9qRTJORGN6TWpnNU1UTjkuWElYMGYtb3pVZmx4dWc2UVJZY0JhNEdDU19mNVZpLVV1QkdtUnFYODU2dw==


###
PUT http://127.0.0.1:6001/v1/u/2
Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFYM0p2YkdVaU9qRXdMQ0oxYVdRaU9qSXNJblZmYm1GdFpTSTZJbUZrYldsdU1TSXNJblZmWVdSa2NpSTZJakV5Tnk0d0xqQXVNU0lzSW1WNGNDSTZNVFkwTnpNeU9UZ3hNeXdpYVdGMElqb3hOalEzTXpJNE9URXpMQ0p1WW1ZaU9qRTJORGN6TWpnNU1UTjkuWElYMGYtb3pVZmx4dWc2UVJZY0JhNEdDU19mNVZpLVV1QkdtUnFYODU2dw==
Content-Type: application/json

{"nickname":"admin11"}
